futbr/blueprints/webui/__init__.py
from flask import Blueprint

from .views import index, campeonato

bp = Blueprint("webui", __name__, template_folder="templates")

bp.add_url_rule("/", view_func=index, endpoint="index")
bp.add_url_rule(
    "/campeonato/<ano>", view_func=campeonato, endpoint="campeonatoview"
)


def init_app(app):
    app.register_blueprint(bp)

futbr/blueprints/webui/views.py
from flask import abort, render_template
from futbr.models import Futbrdata


def index():
    campeonatos = Futbrdata.query.all()
    return render_template("index.html", campeonatos=campeonatos)


def campeonato(ano):
    campeonato = Futbrdata.query.filter_by(ano=ano).first() or abort(
        404, "Campeonato nao encontrado"
    )
    return render_template("campeonato.html", campeonato=campeonato)

futbr/blueprints/webui/templates/campeonato.html
{% extends "index.html" %}
{% block content %}
<div class="container">
<h1>Ano: {{ campeonato.ano }}</h1>

<div class="jumbotron">
<h2>Campeão: {{campeonato.vencedor}}</h2>
<p>
    Vice: {{campeonato.vice}}
</p>
<p>
    Terceiro lugar: {{campeonato.terceiro_colocado}}
</p>
<p>
    Quarto lugar: {{campeonato.quarto_colocado}}
</p>
<p>
    Artilheiro(s): {{campeonato.artilheiros}}
</p>
<p>
    Gols: {{campeonato.gols}}
</p>
</div>
</div>
{% endblock %}

futbr/blueprints/webui/templates/index.html
{% extends "bootstrap/base.html" %}
{% block title %}{{config.get('TITLE')}}{% endblock %}

{% block navbar %}
<div class="navbar">
<div class="navbar-header">
    <a class="navbar-brand" href="{{url_for('webui.index')}}">
    <img alt="Brand" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAB+0lEQVR4AcyYg5LkUBhG+1X2PdZGaW3btm3btm3bHttWrPomd1r/2Jn/VJ02TpxcH4CQ/dsuazWgzbIdrm9dZVd4pBz4zx2igTaFHrhvjneVXNHCSqIlFEjiwMyyyOBilRgGSqLNF1jnwNQdIvAt48C3IlBmHCiLQHC2zoHDu6zG1iXn6+y62ScxY9AODO6w0pvAqf23oSE4joOfH6OxfMoRnoGUm+de8wykbFt6wZtA07QwtNOqKh3ZbS3Wzz2F+1c/QJY0UCJ/J3kXWJfv7VhxCRRV1jGw7XI+gcO7rEFFRvdYxydwcPsVsC0bQdKScngt4iUTD4Fy/8p7PoHzRu1DclwmgmiqgUXjD3oTKHbAt869qdJ7l98jNTEblPTkXMwetpvnftA0LLHb4X8kiY9Kx6Q+W7wJtG0HR7fdrtYz+x7iya0vkEtUULIzCjC21wY+W/GYXusRH5kGytWTLxgEEhePPwhKYb7EK3BQuxWwTBuUkd3X8goUn6fMHLyTT+DCsQdAEXNzSMeVPAJHdF2DmH8poCREp3uwm7HsGq9J9q69iuunX6EgrwQVObjpBt8z6rdPfvE8kiiyhsvHnomrQx6BxYUyYiNS8f75H1w4/ISepDZLoDhNJ9cdNUquhRsv+6EP9oNH7Iff2A9g8h8CLt1gH0Qf9NMQAFnO60BJFQe0AAAAAElFTkSuQmCC">
    </a>
</div>
</div>
{% endblock %}

{% block content %}
<div class="container">
<h1>{{config.get('TITLE')}}</h1>

<div class="jumbotron">
<ul class="list-group">
    {% for campeonato in campeonatos %}
    <li class="list-group-item">
        <a href="{{url_for('webui.campeonatoview', ano=campeonato.ano)}}">{{campeonato.ano}}- {{campeonato.vencedor}}</a>
    </li>
    {% endfor %}
</ul>
</div>

</div>
{% endblock %}